const cardList = [
  {
    image: "/HeroPic.png",
    title: "Featured Project 1",
    description: "Description for featured project 1.",
    author: "Hashmat Ali",
    rating: 4.4,
    tags: ["Robotics", "Automation"],
    price: "Free",
  },
  {
    image: "/LFR-min.png",
    title: "Arduino Line Follower Robot",
    description: "A robot that follows a line path using Arduino and sensors.",
    author: "Ayesha Khan",
    rating: 4.7,
    tags: ["Arduino", "Robotics"],
    price: "Free",
  },
  {
    image: "/BotProject.png",
    title: "Autonomous Bot",
    description: "An autonomous bot designed for object detection and navigation.",
    author: "Ali Raza",
    rating: 4.6,
    tags: ["AI", "Machine Learning"],
    price: "$15",
  },
  {
    image: "/a-photograph-of-a-group-of-five-small-pl_e6FiZoLRTAOYCbn7VCuMvA_7J-UxzJ_Qb-vC7-JnahQWA.jpeg",
    title: "Playful Robot Squad",
    description: "A fun robot project showcasing small collaborative robots.",
    author: "Sana Iqbal",
    rating: 4.8,
    tags: ["Robotics", "Fun"],
    price: "Free",
  },
  {
    image: "/Smartdrone-min.png",
    title: "Smart Drone Delivery System",
    description: "A drone programmed to deliver lightweight packages safely.",
    author: "Bilal Ahmed",
    rating: 4.9,
    tags: ["Drones", "Automation"],
    price: "$25",
  },
  {
    image: "/IOT_HOME-min.png",
    title: "IoT Smart Home",
    description: "A project to control home appliances using IoT and mobile apps.",
    author: "Fatima Noor",
    rating: 4.5,
    tags: ["IoT", "Smart Home"],
    price: "Free",
  },
  {
    image: "/Printer-min.png",
    title: "DIY 3D Printer",
    description: "A cost-effective 3D printer built with open-source parts.",
    author: "Umer Farooq",
    rating: 4.6,
    tags: ["3D Printing", "DIY"],
    price: "$40",
  },
  {
    image: "/AI_Assistnat-min.png",
    title: "AI Chatbot Assistant",
    description: "A chatbot powered by machine learning for customer support.",
    author: "Hira Zaman",
    rating: 4.3,
    tags: ["AI", "Chatbot"],
    price: "Free",
  },
  {
    image: "/Solar_Powered_Card-min.png",
    title: "Solar-Powered Car",
    description: "A small car model that runs on solar energy for sustainability.",
    author: "Ahmed Khan",
    rating: 4.7,
    tags: ["Solar Energy", "Sustainability"],
    price: "$10",
  },
  {
    image: "/Exoskeleton-min.png",
    title: "Robotic Exoskeleton",
    description: "A wearable exoskeleton designed to assist with lifting heavy loads.",
    author: "Zainab Ali",
    rating: 4.9,
    tags: ["Mechatronics", "Robotics"],
    price: "$50",
  },
];

export default cardList;
